IF
AttackedBy([GOODCUTOFF],DEFAULT)
!Allegiance(Myself,ENEMY)
THEN
RESPONSE #100
SetGlobal("O#BrynnlawWallAttack","GLOBAL",1)
Enemy()
END

IF
Global("O#BrynnlawWallAttack","GLOBAL",1)
!Allegiance(Myself,ENEMY)
THEN
RESPONSE #100
Enemy()
END

IF
See(NearestEnemyOf(Myself))
THEN
RESPONSE #100
AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
AttackedBy([ANYONE],DEFAULT)
THEN
RESPONSE #100
Attack(LastAttackerOf(Myself))
END
